# Generated by Django 3.1.4 on 2021-06-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apparel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(choices=[('1', 'grey'), ('2', 'black'), ('3', 'yellow'), ('4', 'blue')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('1', '07'), ('2', '08'), ('3', '09'), ('4', '10')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Color', to='app.color')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Size', to='app.sizes')),
            ],
        ),
    ]
