# Generated by Django 3.1.4 on 2021-06-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Men'), ('2', 'Women')], max_length=15),
        ),
    ]
