# Generated by Django 3.1.4 on 2021-06-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
